app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('hello');
});

Route::get('cristalab', function()
{
    return View::make('cristalab');
});

Route::get('hello/{usuario}', function($usuario)
{
    return "Hello $usuario";
});

Route::get('tags/{tag}', function($tag)
{
    return "You are browsing $tag tag";
});

Route::get('user/edit/{id}', function($id)
{
    return "You are editing the user with the ID #$id";
})
->where('id', '[0-9]+');

Route::get('pasta-with-meatballs/{id_table}, {type}', array('as' => 'pasta_meatballs', 'uses' => 'ItalianController@pastaWithMeatBalls'))->where('id_table', '[0-9]+');

Route::get('template', function () {
   return View::make('template');
});

Route::get('template/{name}', function ($name) {
   $name = ucwords(str_replace('-', ' ', $name));
   return View::make('template')->with('name', $name);
});

Route::resource('admin/users', 'Admin_UsersController');

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');



    public $errors;
    protected $fillable = array('email', 'full_name', 'password');

    public function isValid($data)
    {
        $rules = array(
            'email'     => 'required|email|unique:users',
            'full_name' => 'required|min:4|max:40',
            'password'  => 'min:7|confirmed'
        );

        // Si el usuario existe:
        if ($this->exists)
        {
            //Evitamos que la regla “unique” tome en cuenta el email del usuario actual
            $rules['email'] .= ',email,' . $this->id;
        }
        else // Si no existe...
        {
            // La clave es obligatoria:
            $rules['password'] .= '|required';
        }

        $validator = Validator::make($data, $rules);

        if ($validator->passes())
        {
            return true;
        }

        $this->errors = $validator->errors();

        return false;
    }


    public function setPasswordAttribute($value)
    {
        if ( ! empty ($value))
        {
            $this->attributes['password'] = Hash::make($value);
        }
    }


    public function validAndSave($data)
    {
        // Revisamos si la data es válida
        if ($this->isValid($data))
        {
            // Si la data es valida se la asignamos al usuario
            $this->fill($data);
            // Guardamos el usuario
            $this->save();

            return true;
        }

        return false;
    }

}

app/controllers/admin/UsersController.php
<?php

class Admin_UsersController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$users = User::paginate(5);
        return View::make('admin/users/list')->with('users', $users);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        // Creamos un nuevo objeto User para ser usado por el helper Form::model
        $user = new User;

        $form_data = array('route' => array('admin.users.store', $user->id), 'method' => 'POST');
        $action    = 'Nuevo';

        return View::make('admin/users/form', compact('user', 'form_data', 'action'));
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		// Creamos un nuevo objeto para nuestro nuevo usuario
        $user = new User;

        // Obtenemos la data enviada por el usuario
        $data = Input::all();

        if ($user->validAndSave($data))
        {
            // Y Devolvemos una redirección a la acción show para mostrar el usuario
            return Redirect::route('admin.users.index');
        }
        else
        {
            // En caso de error regresa a la acción create con los datos y los errores encontrados
            return Redirect::route('admin.users.create', $user->id)->withInput()->withErrors($user->errors);
        }
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$user = User::find($id);

        if (is_null ($user))
        {
            App::abort(404);
        }

        return View::make('admin/users/show')->with('user', $user);
    }


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$user = User::find($id);

        if (is_null ($user))
        {
            App::abort(404);
        }

        $form_data = array('route' => array('admin.users.update', $user->id), 'method' => 'PATCH');
        $action    = 'Editar';

        return View::make('admin/users/form', compact('user', 'form_data', 'action'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		// Creamos un nuevo objeto para nuestro nuevo usuario
        $user = User::find($id);

        // Si el usuario no existe entonces lanzamos un error 404 :(
        if (is_null ($user))
        {
            App::abort(404);
        }

        // Obtenemos la data enviada por el usuario
        $data = Input::all();

        if ($user->validAndSave($data))
        {
            // Y Devolvemos una redirección a la acción show para mostrar el usuario
            return Redirect::route('admin.users.index');
        }
        else
        {
            // En caso de error regresa a la acción create con los datos y los errores encontrados
            return Redirect::route('admin.users.edit', $user->id)->withInput()->withErrors($user->errors);
        }
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$user = User::find($id);

        if (is_null ($user))
        {
            App::abort(404);
        }

        $user->delete();

        if (Request::ajax())
        {
            return Response::json(array (
                'success' => true,
                'msg'     => 'Usuario ' . $user->full_name . ' eliminado',
                'id'      => $user->id
            ));
        }
        else
        {
            return Redirect::route('admin.users.index');
        }
	}

}

app/views/admin/users/form.blade.php
@extends ('admin/layout')

<?php
    if ($user->exists):
        $form_data = array('route' => array('admin.users.update', $user->id), 'method' => 'PATCH');
        $action    = 'Editar';
    else:
        $form_data = array('route' => 'admin.users.store', 'method' => 'POST');
        $action    = 'Nuevo';
    endif;
?>


@section ('title')
    {{ $action }} Usuario
@stop


@section ('content')
    <h1 class="text-center">{{ $action }} Usuario</h1>

    {{ Form::model($user, $form_data, array('role' => 'form')) }}
        @include ('admin/errors', array('errors' => $errors))

        <div class="row">
            <div class="form-group col-md-6">
                {{ Form::label('email', 'Dirección de E-mail') }}
                {{ Form::text('email', null, array('placeholder' => 'Introduce tu E-mail', 'class' => 'form-control')) }}
            </div>
            <div class="form-group col-md-6">
                {{ Form::label('full_name', 'Nombre completo') }}
                {{ Form::text('full_name', null, array('placeholder' => 'Introduce tu nombre y apellido', 'class' => 'form-control')) }}
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                {{ Form::label('password', 'Contraseña') }}
                {{ Form::password('password', array('class' => 'form-control')) }}
            </div>
            <div class="form-group col-md-6">
                {{ Form::label('password_confirmation', 'Confirmar contraseña') }}
                {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
            </div>
        </div>

        <div class="pull-right">
            <a href="{{ route('admin.users.index') }}" class="btn btn-default">Cancelar</a>


            {{ Form::button('Guardar', array('type' => 'submit', 'class' => 'btn btn-primary')) }}
        </div>

    {{ Form::close() }}

@stop

app/views/admin/users/list.blade.php
@extends ('admin/layout')

@section ('title')
    Lista de Usuarios
@stop


@section ('content')
    <h1 class="text-center">Lista de usuarios</h1>
    <p class="pull-right">
        <a href="{{ route('admin.users.create') }}" class="btn btn-primary">Nuevo usuario</a>
    </p>

    <table class="table table-striped table-bordered">
        <tr class="info">
            <th class="text-center">Full name</th>
            <th class="text-center">Email</th>
            <th class="text-center">created_at</th>
            <th class="text-center">updated_at</th>
            <th class="text-center">Actions</th>
        </tr>

        @foreach ($users as $user)
            <tr>
                <td>{{ $user->full_name }}</td>
                <td>{{ $user->email }}</td>
                <td class="text-center">{{ $user->created_at }}</td>
                <td class="text-center">{{ $user->updated_at }}</td>
                <td class="text-center">
                    <a href="{{ route('admin.users.show', $user->id) }}" class="btn btn-info btn-xs">
                        Ver
                    </a>
                    <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-primary btn-xs">
                        Editar
                    </a>
                    <a href="#" data-id="{{ $user->id }}" class="btn btn-danger btn-delete btn-xs">
                        Eliminar
                    </a>
                </td>
            </tr>
        @endforeach

    </table>
    <div class="text-center">
        {{ $users->links() }}
    </div>

    {{ Form::open(array('route' => array('admin.users.destroy', 'USER_ID'), 'method' => 'DELETE', 'role' => 'form', 'id' => 'form-delete')) }}
    {{ Form::close() }}

@stop

app/views/admin/users/show.blade.php
@extends ('admin/layout')


@section ('title')
    Usuario {{ $user->full_name }}
@stop


@section ('content')
    <h1 class="text-center">Detalle usuario</h1>
    <p class="pull-right">
        <a href="{{ route('admin.users.index') }}" class="btn btn-default">Regresar</a>
        <a href="{{ route('admin.users.create') }}" class="btn btn-primary">Nuevo usuario</a>
    </p>

    <table class="table table-striped table-bordered">

        <tr class="info">
            <th>Full name</th>
            <th>Email</th>
            <th>created_at</th>
        </tr>

        <tr>
            <td>{{ $user->full_name }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->created_at }}</td>
        </tr>

    </table>

@stop